### ISSUE TITLE
ImportError: attempted relative import with no known parent package

### ISSUE THREAD

**Issue by 1ph** [ix-ai/grafana-email#1]
docker run -it  --name=grafana-email \
>   -e GRAFANA_TOKEN='MyAmazingTokenFromGrafana=' \
>   -e GRAFANA_DASHBOARD="gV6maGVZz/e-mail-reports" \
>   -e SMTP_FROM="test-docker@example.com" \
>   -e SMTP_TO="grafana@example.com" \
>   -e SMTP_HOST="10.0.10.1" \
>   -e PANEL_IDS="2,5,6" \
>   -e PANEL_FROM="now-6h" \
>   -e PANEL_THEME="light" \
>   -e PANEL_TZ="Europe/Berlin" \
>   -e GRAFANA_HOST="grafana1" \
>   -e GRAFANA_PORT="3001" \
>   -e GELF_HOST="graylog" \
>   -e GRAFANA_HEADER_HOST="grafana.example.com" \
>   -e LOGLEVEL="DEBUG" \
>   registry.gitlab.com/ix.ai/grafana-email

Traceback (most recent call last):
  File "/grafana-email/grafana-email.py", line 15, in <module>
    from . import constants
ImportError: attempted relative import with no known parent package

How can I fix it?

**Comment by tlex** [comment]
Thanks for the report. Unfortunately, there's nothing you can do to fix it. I'm looking to implement a fix.

**Comment by tlex** [comment]
Can you please give it a spin with the image `registry.gitlab.com/ix.ai/grafana-email:dev-branch` and let me know if it works for you?

**Comment by 1ph** [comment]
Now everything works correctly. Thank you very much!
