### ISSUE TITLE
Ignore https errors

### ISSUE THREAD

**Issue by rbuffi** [ix-ai/grafana-email#2]
Hello, we are using grafana with https and used the -e GRAFANA_SSL=https option for the grafana-email container.
But certificate validation fails. Is there an option to ignote certificate errors when connecting?

**Comment by tlex** [comment]
Hello,

Indeed, looking at the code, the `verify` param isn't set:
https://github.com/ix-ai/grafana-email/blob/master/grafana-email/grafana-email.py#L92

```py
response = requests.get(uri, params=params, headers=headers, stream=True)
```

Which means, the default `verify=True` is used.

I'll add this option.

**Comment by rbuffi** [comment]
Great, thank  you for the quick response.

**Comment by tlex** [comment]
The pipeline has been completed successfully.

You can test it now:
```
docker pull ixdotai/grafana-email:dev-branch
```

Use the environment variable `GRAFANA_SSL_VERIFY=false` (or `=no` or `=blueberry`, it doesn't matter what you use, if it's not `Y`, `Yes`, `True` etc 🙂 ).

If it works well, I'll merge it to master and create a new release.

**Comment by rbuffi** [comment]
It works like a charm now! Thank you! Just one last question, is it possible to sent the complete dashboard or should the panels always be specified?

**Comment by tlex** [comment]
Happy it works!

Unfortunately (and I've actually researched it), the Grafana API only allows to generate images based on the graphs, it doesn't render the whole web page.

The alternative would be to use https://grafana.com/docs/grafana/v9.0/enterprise/reporting/ - this is already there if you have a license (but, in this case you don't need `grafana-email` anymore 😄 )
